{{- if and (and (.Values.service.enabled) (not .Values.ingress.enabled)) (.Values.targetGroupBinding.enabled) }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
spec:
  serviceRef:
    name: {{ include "app.fullname" . }}
    port: {{ .Values.service.port }}
  targetGroupARN: {{ .Values.targetGroupBinding.targetGroupARN }}
{{- end }}
